AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
  NewCops: enable

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/ExtraSpacing:
  Enabled: false

Layout/LineLength:
  Max: 99

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets